# Generated by Django 2.2.7 on 2019-11-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20191108_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardanswer',
            name='correct',
            field=models.BooleanField(),
        ),
    ]
