# Generated by Django 2.2.7 on 2019-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
