# Generated by Django 2.2.7 on 2019-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20191109_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
