# Generated by Django 2.2.7 on 2019-11-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_group_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='groups',
            field=models.ManyToManyField(blank=True, to='card.Group'),
        ),
    ]
