# Generated by Django 2.2.7 on 2019-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20191110_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('source', 'Source'), ('list', 'List')], default=0, max_length=16),
            preserve_default=False,
        ),
    ]
