# Generated by Django 2.2.7 on 2019-11-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_cardanswer_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='page_offset',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cardanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='card.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='cardanswer',
            unique_together={('session', 'card')},
        ),
    ]
