# Generated by Django 2.2.7 on 2019-12-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_auto_20191123_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='groups',
            field=models.ManyToManyField(blank=True, to='card.Group'),
        ),
    ]
