# Generated by Django 2.2.7 on 2019-12-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_list_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='cards',
        ),
    ]
